Minor update to pr-checks

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -17,6 +17,7 @@ jobs:
     steps:
       - name: Get all artifacts for the repository
         id: list_artifacts
+        shell: bash
         run: |
           output=curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/amruthvvkp/flaui-uiautomation-wrapper/actions/artifacts
           echo "artifacts=$output" >> "$GITHUB_OUTPUT"
@@ -221,15 +222,29 @@ jobs:
       - name: Get latest version from Test PyPI
         id: get_latest_version
         run: |
-          current_version=$(curl -s https://test.pypi.org/pypi/flaui-uiautomation-wrapper/json | jq -r '.releases | keys | sort_by(.) | .[-1]')
+          current_version=$(curl -s https://test.pypi.org/pypi/flaui-uiautomation-wrapper/json | jq -r '.releases | to_entries | sort_by(.value[0].upload_time) | .[-1].key')
           echo "current_version=$current_version" >> "$GITHUB_OUTPUT"
 
       - name: Update package version
         id: update_version
         run: |
           poetry version "${{ steps.get_latest_version.outputs.current_version }}"
-          poetry version prerelease
-          echo "updated_version=$(poetry version | cut -d' ' -f2)" >> $GITHUB_OUTPUT
+          while true; do
+            poetry version prerelease
+            updated_version=$(poetry version | cut -d' ' -f2)
+            url="https://test.pypi.org/simple/flaui-uiautomation-wrapper/flaui_uiautomation_wrapper-$updated_version-py3-none-any.whl"
+            status=$(curl -s -o /dev/null -w "%{http_code}" $url)
+            if [ $status -eq 200 ]; then
+              echo "Package found on Test PyPI for version $updated_version"
+              break
+            elif [ $status -eq 404 ]; then
+              echo "Package not found on Test PyPI for version $updated_version"
+              echo "updated_version=$updated_version" >> $GITHUB_OUTPUT
+            else
+              echo "Error checking Test PyPI status: $status"
+              exit 1
+            fi
+          done
 
       - name: Build and publish distribution 📦 to Test PyPI
         uses: JRubics/poetry-publish@v1.17
